{% set name = "scaffolder" %}
{% set version = "1.5.0a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source: 
  url: https://github.com/nodtem66/Scaffolder/archive/conda-forge.tar.gz
  sha256: 4dd0cea264cdd0081c9383ad52b07683e0e04717e5a5679d72041eeb28426e70

build:
  number: 0
  script:
    - echo "This package can't be built on VS<16" # [win and vs<16]
    - exit 1 # [win and vs<16]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja # [unix]
    - pkg-config # [unix]

test:
  source_files:
    - scripts/stl/
  commands:
    - Scaffolder --help
    - Scaffolder.SliceTest --help

about:
  home: https://github.com/nodtem66/Scaffolder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Generate scaffold from STL/PLY/OFF/OBJ file with implicit function'
  description: |
    Scaffolder is a simple, fast, and complete CLI program to generate
    3D scaffold design for tissue engineering. It is pure C++ code linked
    with dependencies by github submodules. Scaffolder supports predefined
    implit surfaces and custom implicit function though LUA script.  
  doc_url: https://github.com/nodtem66/Scaffolder
  dev_url: https://github.com/nodtem66/Scaffolder

extra:
  recipe-maintainers:
    - nodtem66
